/**
 * Represents a list of categories and the tabs for each category.
 */
export const categories = {
  Items: [
    'Accessories',
    'Artwork',
    'Bags',
    'Bottoms',
    'Clothing Other',
    'Dress-Up',
    'Fencing',
    'Floors',
    'Fossils',
    'Gyroids',
    'Headwear',
    'Housewares',
    'Message Cards',
    'Miscellaneous',
    'Music',
    'Other',
    'Photos',
    'Posters',
    'Rugs',
    'Shoes',
    'Socks',
    'Tools',
    'Tops',
    'Umbrellas',
    'Wall-mounted',
    'Wallpaper',
  ],
  Achievements: ['Achievements'],
  Creatures: ['Fish', 'Insects', 'Sea Creatures'],
  Recipes: ['Recipes'],
  Villagers: ['Villagers'],
  Construction: ['Construction'],
  Reactions: ['Reactions'],
  Translations: ['Translations'],
  SeasonsAndEvents: ['Seasons and Events'],
  NPCs: ['Special NPCs'],
};
