const categories = {
  Items: [
    'Accessories',
    'Art',
    'Bags',
    'Bottoms',
    'Clothing Other',
    'Dress-Up',
    'Fencing',
    'Floors',
    'Fossils',
    'Headwear',
    'Housewares',
    'Message Cards',
    'Miscellaneous',
    'Music',
    'Other',
    'Photos',
    'Posters',
    'Rugs',
    'Shoes',
    'Socks',
    'Tools',
    'Tops',
    'Umbrellas',
    'Wall-mounted',
    'Wallpaper',
  ],
  Achievements: ['Achievements'],
  Creatures: ['Fish', 'Insects', 'Sea Creatures'],
  Recipes: ['Recipes'],
  Villagers: ['Villagers'],
  Construction: ['Construction'],
  Reactions: ['Reactions'],
  IDs: ['IDs'],
  Translations: ['Translations'],
  Events: ['Events', 'Nook Shopping Seasonal'],
  SouthernHemisphere: ['Southern Hemisphere'],
  NorthernHemisphere: ['Northern Hemisphere'],
  NPCs: ['Special NPCs'],
};

export { categories };
